### ISSUE TITLE
Support for promises broken?

### ISSUE THREAD

**Issue by aaronshaf** [raptorjs/marko-async#8]
This works:

```javascript
export default function (req, res) {
  template.render({hello: (callback) => {
    callback(null,'world')
  }}, res)
}
```

This doesn't:

```javascript
export default function (req, res) {
  template.render({hello: () => {
    return new Promise((resolve, reject) => {
      resolve('world?')
    })
  }}, res)
}
```

**Comment by patrick-steele-idem** [comment]
We have a few test cases that make use of promises and those tests are passing. I'll take a closer look to see what the problem might be.

**Comment by aaronshaf** [comment]
Please see my commit. It's because of using the non-standard(?) `.done`

As soon as I removed `.done`, it works just fine with my rsvp/es6-promise promises. Thanks!
